TERRITORY_TO_ABBREV = {
    "Abandoned Farm": "ABF",
    "Abandoned Lumberyard": "ABL",
    "Abandoned Mines": "ABM",
    "Abandoned Mines Entrance": "AME",
    "Abandoned Pass": "ABP",
    "Accursed Dunes": "ACD",
    "Aerial Descent": "ARD",
    "Ahmsord": "AHM",
    "Ahmsord Outskirts": "AHO",
    "Akias Ruins": "AKR",
    "Aldorei Cliffside Waterfalls": "ACW",
    "Aldorei River": "ALR",
    "Aldorei Springs": "ALS",
    "Aldorei Valley": "ALV",
    "Aldorei Valley Outskirts": "AVO",
    "Alekin": "ALK",
    "Almuj": "ALM",
    "Almuj Slums": "AMS",
    "Ancient Excavation": "AEX",
    "Ancient Nemract": "ANM",
    "Ancient Waterworks": "AWW",
    "Angel Refuge": "ARF",
    "Apprentice Huts": "APH",
    "Arachnid Woods": "ARW",
    "Astraulus' Tower": "AST",
    "Ava's Workshop": "AVW",
    "Avos Temple": "AVT",
    "Avos Territory": "AVY",
    "Azure Frontier": "AZF",
    "Balloon Airbase": "BAB",
    "Bandit Cave": "BCV",
    "Bandit's Toll": "BTL",
    "Bantisu Air Temple": "BAT",
    "Bantisu Approach": "BTA",
    "Barren Sands": "BRS",
    "Bear Zoo": "BRZ",
    "Big Mushroom Cave": "BMC",
    "Bizarre Passage": "BZP",
    "Black Road": "BLR",
    "Blackstring Den": "BSD",
    "Bloody Beach": "BBH",
    "Bloody Trail": "BTR",
    "Blooming Boulders": "BLB",
    "Bob's Tomb": "BOB",
    "Bremminglar": "BRM",
    "Brigand Outpost": "BOP",
    "Broken Road": "BKR",
    "Bucie Waterfall": "BCW",
    "Burning Airship": "BAS",
    "Burning Farm": "BFM",
    "Canyon Dropoff": "CDO",
    "Canyon High Path": "CHP",
    "Canyon Walkway": "CWY",
    "Caritat Mansion": "CRM",
    "Cascading Basins": "CSB",
    "Cascading Oasis": "CSO",
    "Castle Dullahan": "CDH",
    "Cathedral Harbour": "CTH",
    "Celestial Impact": "CLI",
    "Centerworld Fortress": "CWF",
    "Central Islands": "CTI",
    "Chasm Chokepoint": "CCH",
    "Chasm Overlook": "CHO",
    "Cherry Blossom Grove": "CBG",
    "Cinfras": "CIN",
    "Cinfras Outskirts": "CIO",
    "Cinfras's Small Farm": "CSF",
    "Cliffhearth Orc Camp": "COC",
    "Cliffside Passage North": "CPN",
    "Cliffside Passage South": "CPS",
    "Coastal Trail": "CTL",
    "Collapsed Bridge": "CLB",
    "Collapsed Emerald Mine": "CEM",
    "Colourful Mountaintop": "CMT",
    "Corkus Castle": "CKC",
    "Corkus City": "CC",
    "Corkus City Crossroads": "CCC",
    "Corkus City Mine": "CCM",
    "Corkus Forest": "CKF",
    "Corkus Outskirts": "CKO",
    "Corkus Sea Cove": "CSC",
    "Corrupted Orchard": "CRO",
    "Corrupted River": "CRR",
    "Corrupted Road": "CRD",
    "Corrupted Tower": "CRT",
    "Corrupted Warfront": "CWR",
    "Cosmic Fissures": "CMF",
    "Crater Descent": "CRD2",
    "Cyclospordial Hazard": "CYH",
    "Dark Forest Village": "DFV",
    "Decayed Basin": "DCB",
    "Delnar Manor": "DLM",
    "Derelict Mansion": "DRM",
    "Desolate Valley": "DSV",
    "Detlas": "DET",
    "Detlas Suburbs": "DTS",
    "Displaced Housing": "DPH",
    "Disturbed Crypt": "DBC",
    "Dodegar's Forge": "DGF",
    "Dogun Ritual Site": "DRS",
    "Dragonbone Graveyard": "DBG",
    "Dragonling Nests": "DLN",
    "Dreary Docks": "DRD",
    "Dujgon Nation": "DJN",
    "Durum Barley Islet": "DBI",
    "Durum Isles Barn": "DIB",
    "Durum Malt Islet": "DMI",
    "Durum Oat Islet": "DOI",
    "Dusty Pit": "DPT",
    "Eagle Tribe": "EGT",
    "Efilim": "EFL",
    "Efilim Crossroads": "EFC",
    "Elefolk Stomping Grounds": "ESG",
    "Elephelk Trail": "ELT",
    "Elkurn": "ELK",
    "Eltom": "ELM",
    "Emerald Trail": "EMT",
    "Enchanted River": "ECR",
    "Entamis Village": "ENV",
    "Entrance to Almuj": "ETA",
    "Entrance to Bucie": "ETB",
    "Entrance to Cinfras": "ETC",
    "Entrance to Gavel": "ETG",
    "Entrance to Kander": "ETK",
    "Entrance to Molten Heights": "EMH",
    "Entrance to Nivla Woods": "ENW",
    "Entrance to Olux": "ETO",
    "Entrance to Thesead": "ETT",
    "Essren's Hut": "ESH",
    "Evergreen Outbreak": "EGO",
    "Fading Forest": "FDF",
    "Fallen Factory": "FFY",
    "Fallen Village": "FVL",
    "Faltach Manor": "FTM",
    "Farmers Settlement": "FMS",
    "Featherfall Cliffs": "FFC",
    "Felroc Fields": "FRF",
    "Field of Life": "FOL",
    "Final Step": "FNS",
    "Fleris Cranny": "FLC",
    "Fleris Trail": "FLT",
    "Floral Peaks": "FLP",
    "Florist's Hut": "FLH",
    "Forest of Eyes": "FOE",
    "Forgotten Burrows": "FGB",
    "Forgotten Path": "FGP",
    "Forgotten Town": "FGT",
    "Founder's Statue": "FDS",
    "Fountain of Youth": "FOY",
    "Freezing Heights": "FZH",
    "Frigid Crossroads": "FCR",
    "Frosty Spikes": "FSP",
    "Frozen Fort": "FFT",
    "Frozen Homestead": "FHS",
    "Fungal Grove": "FNG",
    "Gateway to Nothing": "GTN",
    "Gelibord": "GLB",
    "Gelibord Watermill": "GWM",
    "Gert Camp": "GTC",
    "Gloopy Cave": "GLC",
    "Goblin Plains East": "GPE",
    "Goblin Plains West": "GPW",
    "Great Bridge": "GBR",
    "Grey Ruins": "GRR",
    "Guardian of the Forest": "GOF",
    "Guild Hall": "GHL",
    "Gylia Fisherman Camp": "GFC",
    "Gylia Lakehouse": "GLH",
    "Gylia Research Cabin": "GRC",
    "Gylia Watchtower": "GWT",
    "Half Moon Island": "HMI",
    "Harnort Compound": "HNC",
    "Harpy's Haunt North": "HHN",
    "Harpy's Haunt South": "HHS",
    "Heart of Decay": "HOD",
    "Heavenly Ingress": "HVI",
    "Herb Cave": "HBC",
    "Hobgoblin's Hoard": "HGH",
    "Housing Crisis": "HCR",
    "Iboju Village": "IBV",
    "Icy Descent": "ICD",
    "Icy Island": "ICY",
    "Icy Vigil": "ICV",
    "Illuminant Path": "ILP",
    "Industrial Clearing": "INC",
    "Infested Sinkhole": "ISH",
    "Inhospitable Mountain": "IHM",
    "Invaded Barracks": "INB",
    "Iron Road": "IRR",
    "Jagged Foothills": "JGF",
    "Jitak's Farm": "JTF",
    "Jofash Docks": "JFD",
    "Jofash Tunnel": "JFT",
    "Jungle Entrance": "JNE",
    "Kander Mines": "KDM",
    "Kandon Farm": "KNF",
    "Kandon Ridge": "KNR",
    "Kandon-Beda": "KNB",
    "Karoc Quarry": "KRQ",
    "Katoa Ranch": "KTR",
    "Kitrios Armory": "KTA",
    "Kitrios Barracks": "KTB",
    "Krolton's Cave": "KRC",
    "Lava Lakes": "LVL",
    "Lava Springs": "LVS",
    "Legendary Island": "LGI",
    "Lexdale": "LXD",
    "Lexdale Penitentiary": "LXP",
    "Lifeless Forest": "LLF",
    "Light Peninsula": "LPN",
    "Lighthouse Lookout": "LHL",
    "Lion Lair": "LNL",
    "Little Wood": "LTW",
    "Lizardman Camp": "LZC",
    "Lizardman Lake": "LZL",
    "Llevigar": "LLV",
    "Llevigar Farm": "LVF",
    "Llevigar Gate": "LVG",
    "Llevigar Stables": "LVB",
    "Loamsprout Orc Camp": "LOC",
    "Lost Atoll": "LAT",
    "Luminous Plateau": "LMP",
    "Lusuco": "LSC",
    "Lutho": "LTH",
    "Luxuriant Pond": "LXP2",
    "Mage Island": "MGI",
    "Maiden Tower": "MDT",
    "Maltic": "MLT",
    "Maltic Coast": "MLC",
    "Mangled Lake": "MGL",
    "Mantis Nest": "MNT",
    "Maro Peaks": "MRP",
    "Mesquis Tower": "MST",
    "Meteor Crater": "MTC",
    "Meteor Trail": "MTR",
    "Mine Base Plains": "MBP",
    "Mining Base Camp": "MBC",
    "Minotaur Barbecue": "MNB",
    "Molten Passage": "MPS",
    "Molten Reach": "MLR",
    "Monte's Village": "MTV",
    "Mount Wynn Inn": "MWI",
    "Mudspring Orc Camp": "MOC",
    "Mummy's Tomb": "MMT",
    "Mushroom Hill": "MSH",
    "Mycelial Expanse": "MYE",
    "Myconid Descent": "MYD",
    "Naga Lake": "NGL",
    "Nemract": "NMR",
    "Nemract Cathedral": "NMC",
    "Nesaak": "NSK",
    "Nesaak Transition": "NST",
    "Nested Cliffside": "NCS",
    "Nexus of Light": "NOL",
    "Nivla Woods": "NVW",
    "Nivla Woods Exit": "NWE",
    "Nodguj Nation": "NDN",
    "Nomads' Refuge": "NRF",
    "Ogre Den": "OGD",
    "Old Coal Mine": "OCM",
    "Old Crossroads": "OCR",
    "Olux": "OLX",
    "Olux Lumberyard": "OLY",
    "Orc Battlegrounds": "OBG",
    "Orc Lake": "ORL",
    "Orc Road": "ORR",
    "Otherworldly Monolith": "OWM",
    "Outer Aldorei Town": "OAT",
    "Overrun Docks": "OVD",
    "Overtaken Outpost": "OTO",
    "Owl Tribe": "OWT",
    "Panda Kingdom": "PDK",
    "Panda Path": "PDP",
    "Paper Trail": "PPT",
    "Parasitic Slime Mine": "PSM",
    "Path to Ahmsord": "PTA",
    "Path to Cinfras": "PTC",
    "Path to Light": "PTL",
    "Path to Light's Secret": "PLS",
    "Path to Ozoth's Spire": "POS",
    "Path to Talor": "PTT",
    "Path to Thanos": "PTH",
    "Path to the Dojo": "PTD",
    "Path to the Forgery": "PTF",
    "Path to the Grootslangs": "PTG",
    "Path to the Penitentiary": "PTP",
    "Paths of Sludge": "POS2",
    "Perilous Grotto": "PGT",
    "Perilous Passage": "PPG",
    "Picnic Pond": "PCP",
    "Pigmen Ravines": "PMR",
    "Pine Pillar Forest": "PPF",
    "Pirate Town": "PRT",
    "Plains Lake": "PLK",
    "Primal Fen": "PMF",
    "Protector's Pathway": "PRW",
    "Pyroclastic Flow": "PCF",
    "Ragni": "RAG",
    "Ragni Countryside North": "RCN",
    "Ragni Countryside South": "RCS",
    "Ragni Main Entrance": "RME",
    "Ragni North Entrance": "RNE",
    "Ragni South Entrance": "RSE",
    "Raiders' Airbase": "RAB",
    "Raiders' Stronghold": "RSH",
    "Ranol's Farm": "RNF",
    "Razed Inn": "RZI",
    "Regular Island": "RGI",
    "Relos": "RLS",
    "Retrofitted Manufactory": "RTM",
    "Riverbank Knoll": "RBK",
    "Road to Elkurn": "RTE",
    "Road to Light Forest": "RLF",
    "Road to Mine": "RTM2",
    "Road to Time Valley": "RTV",
    "Rocky Bend": "RKB",
    "Rocky Shore": "RKS",
    "Rodoroc": "RDR",
    "Rooster Island": "RSI",
    "Roots of Corruption": "ROC",
    "Royal Gate": "RYG",
    "Ruined Houses": "RNH",
    "Ruined Prospect": "RNP",
    "Ruined Villa": "RNV",
    "Rymek": "RYM",
    "Sablestone Orc Camp": "SOC",
    "Sanctuary Bridge": "SCB",
    "Sanguine Spider Den": "SSD",
    "Santa's Hideout": "STH",
    "Savannah Plains": "SVP",
    "Scorched Trail": "SCT",
    "Scorpion Nest": "SPN",
    "Secluded Ponds": "SCP",
    "Secluded Workshop": "SCW",
    "Selchar": "SEL",
    "Shady Shack": "SDS",
    "Shineridge Orc Camp": "SRC",
    "Silent Road": "SLR",
    "Silverbull Headquarters": "SBH",
    "Sinister Forest": "SNF",
    "Skien's Island": "SKI",
    "Sky Castle": "SKC",
    "Sky Falls": "SKF",
    "Sky Island Ascent": "SIA",
    "Snail Island": "SNI",
    "Southern Outpost": "SOP",
    "Stonecave Orc Camp": "STC",
    "Sulphuric Hollow": "SPH",
    "Sunrise Plateau": "SRP",
    "Sunset Plateau": "SNP",
    "Sunspark Orc Camp": "SSO",
    "Swamp Island": "SWI",
    "Swamp Mountain Arch": "SMA",
    "Talor Cemetery": "TLC",
    "Temple Island": "TPI",
    "Temple of Legends": "TOL",
    "Tempo Town": "TMT",
    "Ternaves": "TRN",
    "Ternaves Tunnel": "TRT",
    "Thanos": "THA",
    "Thanos Exit": "THE",
    "Thanos Underpass": "THU",
    "The Forgery": "TFG",
    "The Gate": "TGT",
    "The Hive": "THV",
    "The Shiar": "TSH",
    "Thesead": "TSD",
    "Thesead Suburbs": "TSS",
    "Thesead Underpass": "TSU",
    "Time Valley": "TMV",
    "Timeworn Arch": "TWA",
    "Tower of Ascension": "TOA",
    "Toxic Caves": "TXC",
    "Toxic Drip": "TXD",
    "Tree Island": "TRI",
    "Troll Tower": "TLT",
    "Troll's Challenge": "TRC",
    "Troms": "TRM",
    "Troms Lake": "TRL",
    "Trunkstump Goblin Camp": "TGC",
    "Turncoat Turnabout": "TCT",
    "Twain Lake": "TWL",
    "Twain Mansion": "TWM",
    "Twisted Housing": "TWH",
    "Twisted Ridge": "TWR",
    "Unicorn Trail": "UNT",
    "Upper Thanos": "UTH",
    "Viscera Pits": "VCP",
    "Void Valley": "VDV",
    "Volcanic Excavation": "VLE",
    "Volcanic Isles": "VLI",
    "Wanderer's Way": "WDW",
    "Waterfall Cave": "WFC",
    "Wayward Split": "WWS",
    "Webbed Fracture": "WBF",
    "Weird Clearing": "WRC",
    "Winding Waters": "WWW",
    "Witching Road": "WTR",
    "Wizard Tower": "WZT",
    "Wizard's Warning": "WZW",
    "Wolves' Den": "WLD",
    "Wood Sprite Hideaway": "WSH",
    "Workshop Glade": "WKG",
    "Worm Tunnel": "WMT",
    "Wybel Island": "WBI",
    "Zhight Island": "ZHI",
}
